/* 
 * A Bit of Everything
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: none@example.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package abe

type ExamplepbMimicObjectResponseSuccess struct {

	Code int32 `json:"code,omitempty"`

	Message string `json:"message,omitempty"`

	Status string `json:"status,omitempty"`
}
