/* 
 * examples/proto/examplepb/unannotated_echo_service.proto
 *
 * Unannotated Echo Service Similar to echo_service.proto but without annotations. See unannotated_echo_service.yaml for the equivalent of the annotations in gRPC API configuration format.  Echo Service API consists of a single service which returns a message.
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package unannotatedecho

type ExamplepbUnannotatedSimpleMessageSuccess struct {

	Code int32 `json:"code,omitempty"`

	Message string `json:"message,omitempty"`

	Status string `json:"status,omitempty"`
}
