/* 
 * Echo Service
 *
 * Echo Service API consists of a single service which returns a message.
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package echo

type ExamplepbSimpleMessageSuccess struct {

	Code int32 `json:"code,omitempty"`

	Message string `json:"message,omitempty"`

	Status string `json:"status,omitempty"`
}
